name: Deploy static site to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies (optional)
        run: |
          if [ -f package.json ]; then npm ci --silent || true; fi

      - name: Build (none)
        run: echo "No build step - copying files"

      - name: Archive site for Pages
        id: archive
        if: runner.os == 'Linux' || runner.os == 'macOS' || runner.os == 'Windows'
        shell: bash
        run: |
          set -e
          ART=artifact.tar
          if [ "$RUNNER_OS" = "Windows" ]; then
            tar -cvf "$RUNNER_TEMP\\$ART" --force-local . --exclude=.git --exclude=.github
            echo "ART_PATH=$RUNNER_TEMP\\$ART" >> $GITHUB_OUTPUT
          else
            tar -cvf "$RUNNER_TEMP/$ART" --exclude=.git --exclude=.github .
            echo "ART_PATH=$RUNNER_TEMP/$ART" >> $GITHUB_OUTPUT
          fi

      - name: Upload Pages artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ${{ steps.archive.outputs.ART_PATH || format('{0}/artifact.tar', env.RUNNER_TEMP) }}
          retention-days: 1

      - name: Publish
        uses: actions/deploy-pages@v1
